### ISSUE TITLE
API 테스트 정의

### ISSUE THREAD

**Issue by hbeeni** [hbeeni/online-store-project#15]
API 테스트 골격을 잡는다.

## TODO
* [ ] 상품 API 테스트 정의
* [ ] 카테고리 API 테스트 정의
* [ ] 장바구니 API 테스트 정의
* [ ] 주문 API 테스트 정의
* [ ] 회원 API 테스트 정의
* [ ] 회원가입, 로그인 API 테스트 정의
