### ISSUE TITLE
상품 API 컨트롤러 구현

### ISSUE THREAD

**Issue by hbeeni** [hbeeni/online-store-project#76]
이전에 작성했던 상품 API 컨트롤러 테스트를 보완하고, 구현한다.

### TODO
* [x] 상품 Request 검증 추가
* [x] 상품 API 컨트롤러 테스트 보완
* [x] 상품 API 컨트롤러 구현

### Reference
- #16
